[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "npm ci --include=dev",
    "cd server && npm ci --only=production"
]

[phases.build]
cmds = [
    "npm run build",
    "mkdir -p server/public",
    "cp -r dist/* server/public/"
]

[start]
cmd = "cd server && npm start"