[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "npm ci --include=dev",
    "cd server && npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd server && npm start"